const Order = require("../models/Order");
exports.createOrder = async (req, res) => {
  try {
    const { customerName, phone, items, screenNumber } = req.body;

    if (!customerName || !phone || !items || !items.length) {
      return res.status(404).json({ message: "Missing required fields" });
    }

    let total = 0;
    console.log(items);

    items.map((item) => {
      total += item.snackPrice;
    });
    const order = new Order({
      //   customer,
      customerName,
      phone,
      screenNumber,
      items,
      totalPrice: total,
      // orderId auto-generated by schema default
    });

    await order.save();
    res.status(201).json(order);
  } catch (error) {
    console.error(error);
    // Handle duplicate orderId errors and validation errors
    if (error.code === 11000) {
      return res
        .status(400)
        .json({ message: "Duplicate orderId, please try again" });
    }
    res.status(500).json({ message: error.message });
  }
};
